### ISSUE TITLE
error launched by s2-create-acl-domains

### ISSUE THREAD

**Issue by erbrito** [grails-plugins/grails-spring-security-acl#18]
Running on grails 3.1.1 with groovy 2.4.5 and java 1.8

using those versions of the plugins

compile 'org.grails.plugins:spring-security-core:3.0.3'
runtime 'org.grails.plugins:spring-security-acl:3.0.1'

I got an error with the following message:

s2-create-acl-domains| Error Command [s2-create-acl-domains] error: Error rendering template [_AclClass.groovy] to destination domain/grails/plugin/springsecurity/acl/AclClass.groovy: No such property: id for class: groovy.lang.Binding

It is created at the root level the folder /domain/grails/plugin/springsecurityh/acl

I guess that acl plugin (3.0.1) is not compatible with grails 3.1.1

**Comment by qinshulei** [comment]
I have same problem.Running on grails 3.0.17.

**Comment by markoschnecke** [comment]
Same here. I'm using grails 3.1.10.

**Comment by KentDevWeb** [comment]
I've same problem.
Running on Grails 3.2.0 (JDK 1.8)

**Comment by jameskleeh** [comment]
Fixed in 3.1.0
